#!/usr/bin/perl

# Unit testing for PPI, generated by Test::Inline

use strict;
use File::Spec::Functions ':ALL';
BEGIN {
	$|  = 1;
	$^W = 1;
	$PPI::XS_DISABLE = 1;
	$PPI::XS_DISABLE = 1; # Prevent warning
}
use PPI;

# Execute the tests
use Test::More tests => 12;

# =begin testing string 12
{
my @comments = ("print 1; # comment", "# comment", "print 1; # comment\n", "# comment\n");

foreach my $comment (@comments) {
   my $Document = PPI::Document->new( \$comment );
   isa_ok( $Document, 'PPI::Document' );
   my $Comment = $Document->find_first('Token::Comment');
   isa_ok( $Comment, 'PPI::Token::Comment' );
   is( $Comment->content, '# comment', "->content for line '$comment' returns as expected" );
   }
}

1;
