---
name: dzil build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    name: List Perl versions
    outputs:
      versions-perl:    ${{ steps.action.outputs.versions-target-perl }}
      versions-macos:   ${{ steps.action.outputs.versions-target-macos }}
      versions-windows: ${{ steps.action.outputs.versions-target-windows-strawberry }}
    steps:
      - id: action
        uses: perl-actions/multi-target-perl-versions@v2
        with:
          since-perl:                     5.8
          with-target-perl:               true
          with-target-macos:              true
          with-target-windows-strawberry: true

  build-job:
    name: Build distribution
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.38
    steps:
      - uses: actions/checkout@v6
      - name: Run Tests
        env:
          AUTHOR_TESTING: 0
          AUTOMATED_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
        run: auto-build-and-test-dist
      - uses: actions/upload-artifact@v7
        with:
          name: build_dir
          path: build_dir
  coverage-job:
    needs: build-job
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.38
    steps:
      - uses: actions/checkout@v6 # codecov wants to be inside a Git repository
      - uses: actions/download-artifact@v8
        with:
          name: build_dir
          path: .
      - name: install authordeps
        run: dzil authordeps --missing | cpanm
      - name: install deps
        run: dzil listdeps --missing --author | cpanm
      - name: Install deps and test
        run: cpan-install-dist-deps && test-dist
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
  ubuntu-test-job:
    needs:
      - build-job
      - perl-versions
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      matrix:
        perl-version: ${{ fromJson (needs.perl-versions.outputs.versions-perl) }}
    name: Perl ${{ matrix.perl-version }} on ubuntu-latest
    steps:
      - name: set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - uses: actions/download-artifact@v8
        with:
          name: build_dir
          path: .
      - name: install deps using cpanm
        uses: perl-actions/install-with-cpanm@v2
        with:
          args: " --installdeps ."
      - name: Run tests
        run: prove -lr t
        env:
          AUTHOR_TESTING: 0
          RELEASE_TESTING: 0
  macos-test-job:
    needs:
      - ubuntu-test-job
      - perl-versions
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson (needs.perl-versions.outputs.versions-macos) }}
    name: perl ${{ matrix.perl-version }} on macos-latest
    steps:
      - name: set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - uses: actions/download-artifact@v8
        with:
          name: build_dir
          path: .
      - name: install deps using cpanm
        uses: perl-actions/install-with-cpanm@v2
        with:
          args: " --verbose --installdeps ."
      - run: prove -lr t
        env:
          AUTHOR_TESTING: 0
          RELEASE_TESTING: 0
  windows-test-job:
    needs:
      - ubuntu-test-job
      - perl-versions
    runs-on: "windows-latest"
    strategy:
      fail-fast: true
      matrix:
        perl-version: ${{ fromJson (needs.perl-versions.outputs.versions-windows) }}
    name: perl ${{ matrix.perl-version }} on windows-latest
    steps:
      - name: set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          distribution: strawberry # this option only used on windows
      - uses: actions/download-artifact@v8
        with:
          name: build_dir
          path: .
      - name: install deps using cpanm
        uses: perl-actions/install-with-cpanm@v2
        with:
          args: " --installdeps ."
      - run: prove -lr t
        env:
          AUTHOR_TESTING: 0
          RELEASE_TESTING: 0
